[workspace]
authors = ["Jordan Kanter <jikanter@gmail.com>"]
channels = ["conda-forge"]
name = "pylisp"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
test = "bash test.sh"

[dependencies]
python = "3.12.*"
click = ">=8.4.2,<9"
